kind: Deployment
apiVersion: apps/v1
metadata:
  name: webdeploy
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      name: testpod1
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: httpd
        ports:
        - containerPort: 80
