apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: storage-lab
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-storage
          mountPath: /mnt/data
  volumes:
    - name: host-storage
      hostPath:
        path: /data/hostpath
        type: DirectoryOrCreate
